### ISSUE TITLE
allow building using the non-forked version of blis as packaged by Debian

### ISSUE THREAD

**Issue by pabs3** [explosion/cython-blis#32]
My employer has tasked me with packaging spaCy and gensim for Debian and as part of that I need to package cython-blis for Debian.

Since Debian prefers not to use embedded code copies and prefers to use the primary upstream rather than forks, it would be nice to be able to build cython-blis against the work of @cdluminate, who has packaged @flame's version of blis for Debian.

I propose to have all changes from @honnibal's fork of blis merged into @flame's version, then remove the flame-blis git submodule (which is actually honnibal's fork) from cython-blis, then remove the vendored copy of the flame-blis git submodule, then update the cython-blis build system to build against the installed version of blis and finally probably have the cython-blis CI clone and build the @flame version of blis.

If this isn't acceptable then an option for setup.py to not build the vendored copy of blis and instead link against the already installed version would be a reasonable compromise. For the Debian package of cython-blis I would then remove the vendored copy of blis from the tarball.

I'm happy to work on either of these options as you prefer, but switching cython-blis to always use the flame version of blis would be preferable to me.

**Comment by honnibal** [comment]
Hey,

So, I think there might be two separate issues here.

1) What do you mean by "packaging spaCy for Debian"?

I think it'd be cool to have spaCy packaged as a CLI application for Debian. I've been thinking about doing that actually. If you checkout the spaCy repo and run `make` you get a self-contained executable, that only depends on the system's Python. I think it'd be cool to have this as a Debian package, but I'd like for Explosion to maintain it, so that we can keep it up to date.

On the other hand, if you mean a Debian package of the library that is installed via the system package manager and ends up in the system Python, then I'm absolutely opposed to that and I will fight you to stop it happening. Python libraries should not be available on the system package manager, and especially for a large library fast-moving library like spaCy that relies on several other packages, it would cause a lot of problems.

2) cython-blis depending a shared library

I think it'd be reasonable to allow `cython-blis` to link against a shared library as an option, instead of compiling its own. I wouldn't want a hypothetical Debian CLI version to use this workflow though. I'd like the distributed version to use the same code-paths that people normally use.

**Comment by pabs3** [comment]
By "packaging spaCy for Debian" I mean make spaCy available in Debian
as a package available via apt-get install, like any other Debian
package.

Another Debian contributor @iurshina has already started working on
this in 2018, long before I started looking at spaCy packaging and
their work is available on Debian's GitLab instance:

https://salsa.debian.org/science-team/spacy

I also noticed that there is a repository here containing files for
building a .deb package containing spacy and spacy-services:

https://github.com/opensemanticsearch/spacy-services.deb

My employer only does software deployment via Debian source & binary
packages, currently we have an internal package of spaCy and we simply
considered polishing it and contributing our efforts back to Debian.

So there does seem to be demand for installing spacy via .deb files,
which isn't currently available publicly in completed/polished form.

A Debian CLI package can't build against or depend on any external
packages so a spaCy CLI Debian package would have to be accompanied by
a spaCy Python library package in order to work.

I would welcome help from the Explosion team in getting spaCy and its
dependencies packaged for Debian. I'll be happy to sponsor any package
that is compliant with Debian Policy and related to spaCy or gensim.

There are currently 4278 library packages for Python 3 available in
Debian bullseye, some of them like thinc are from the Explosion team
and they all provide a lot of value to Debian users. For example the
thinc package is present in the Debian Science Team's linguistics task,
along with a TODO item for getting spaCy into Debian.

https://blends.debian.org/science/tasks/linguistics

In order to get cython-blis into Debian (it is needed to update the
Debian package of thinc), it would indeed need to link against Debian's
blis shared libraries as it is against Debian Policy to link against
libraries external to Debian or to vendor such libraries.

Since my employer needs the spaCy and gensim stacks in Debian I will
commit to keeping them up to date and including recent versions in the
Debian backports suites. I have to do that anyway for our internal
Debian packages so it isn't much more work to get them into Debian.

I think that having spaCy available to users of Debian, Ubuntu and
other Debian derivatives could generate more profits for Explosion AI
by exposing your software to a wider audience, some of whom would want
to come to you in order to use Prodigy.

If you still object to us sharing our work with the Debian community
(and thus with Ubuntu and other Debian derivatives) then I will let my
employer know of your decision but ultimately it will be up to them. We
do try to be good actors in the open source community though so it is
somewhat likely they will respect your wishes in this situation.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by cdluminate** [comment]
For "packages that relies on several other packages", system package managers such as apt can usually manifest their higher reliability compared to the other solutions. Indeed all the ways have pros and cons, but is it really a good idea to demotivate initiative volunteers on contributing another possibility, solely based on several cons?

**Comment by honnibal** [comment]
>  is it really a good idea to demotivate initiative volunteers on contributing another possibility, solely based on several cons?

I'm honestly not usually like this. But I feel strongly that this would be extremely bad for both users and us. It will mean that a lot of new users will send themselves down an incorrect installation path that messes up their system and leaves it in a state that's confusing and annoying. It'll then be up to us to help them out of it. So yes, I want to demotivate initiative volunteers from doing something bad!

> My employer only does software deployment via Debian source & binary packages

I think this policy is pretty dumb, and I would quit anywhere that had this. But surely this means you mostly can't use the system packages for the different Python libraries you're trying to use anyway, right? They'll all be different versions than what you need. If you push this version of spaCy, in two years it'll be about two years out-of-date, so you'll be building your own internal versions anyway.

> For example the thinc package is present in the Debian Science Team's linguistics task, along with a TODO item for getting spaCy into Debian.

I'm sad and frustrated to hear that, but at least few people are installing Thinc independently, so it's had low impact. Here's a good example question: what version of Thinc will that install? I can't even tell, but it's obviously very old.

So let's say users are using this linguistics package. Now if they try to install spaCy alongside it, they won't be able to: the versions of Thinc required will be incompatible. Python libraries are not like .so files, where you can have multiple versions of the same library installed at once. In the system Python, there can only be one version of each library. So suddenly, the authors of this linguistics package will be getting requests to update to the new version of Thinc...Which is quite different from the one they are using.

As time passes, more of these inter-package dependencies will arise, which will lock the Debian versions onto old versions of spaCy. This means that when you do "apt install spacy-python3", you'll get some old version that won't support the user's 3d card or CUDA environment, won't be compatible with current models, and will require different documentation. Users will then abandon this path and go and install spaCy the way they should do, over pip or conda or by getting a statically linked executable. This will leave them with this ghost copy of "spacy" in their system. Sometimes they will type `spacy download en_core_web_sm`, and access the wrong version of spaCy. Sometimes their jupyter notebook will not be running inside a virtualenv, and the wrong spaCy will be imported. Sometimes a subprocess will be run that doesn't access the right environment. These are all terrible errors.

Explosion believes that machine learning and natural language processing often require domain expertise. You need to understand a problem and context to get the best use out of them. We are delighted to be helping many users who have programming as a "side arm", not their main thing. We are very inspired by what historians, geoscientists, lawyers, doctors and others have been able to do with a relatively small investment in programming skills. What kills us is how incidentally hard everything is.

Installing Python packages via "apt" looks so tempting, because it's how other software is installed. So it looks like the right way to try out this machine learning thing you're dabbling with. But then you get an old version that doesn't work with the tutorial you're trying to follow, doesn't support the features you saw on the website that got you interested in it, and might mess up the rest of your system, stopping you from doing the work you actually need to do? I want to prevent that.

So frankly I read this request as "Will you help me make this worse?", and my answer is "no". I will fight you.

**Comment by cdluminate** [comment]
@honnibal Thanks for the explanation. I think you have made the point clear, and my personal experience is that letting the users install python stuff with conda could make their life easier (even if the conda style contradicts the convention of FOSS communities such as Debian), especially for those who cannot diagnose the python dependency mess.

As an AI researcher (one of my research projects adopted spaCy) and a Debian developer at the same time, I understand both sides so it's hard for me to lean towards any side instead of keeping neutral.

**Comment by pabs3** [comment]
My employer has made the decision to stop working on getting spaCy into
Debian for now. We may revisit the decision at a later time. In the
meantime we will continue using and maintaining our internal Debian
packages of spaCy and its dependencies. Of course other folks in Debian
or other distributions such as RedHat might also package spaCy at some
point in the future. So you might want to update the Explosion AI and
spaCy/thinc websites to say that users of packages other than the ones
you distribute yourselves via PyPi are unsupported. You can close this
issue and the one I filed about parallel builds, since they are only
really needed by third-party packages repositories like Debian and
everyone else will use your prebuilt packages so they won't require
build improvements as they won't be doing builds.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
