### ISSUE TITLE
blis not compiling / installing on Windows 10

### ISSUE THREAD

**Issue by d97hah** [explosion/cython-blis#8]
[clangerr.txt](https://github.com/explosion/cython-blis/files/3080080/clangerr.txt)

**Comment by d97hah** [comment]
I should say this is for Python 2.7

**Comment by 0h** [comment]
> Wheels should be available, so installation should be fast. If you want to install from source and you're on Windows, you'll need to install LLVM.

you need to install llvm for windows first

**Comment by yeyoushun** [comment]
I got the same error as yours!

**Comment by yuningDING** [comment]
Same here with Python 3.7 and Windows 10.
``(mypython) C:\Users\gixig\mypython\Scripts>pip install C:\Users\gixig\Downloads\blis-0.2.4-cp37-cp37m-win_amd64.whl
ERROR: blis-0.2.4-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by yeyoushun** [comment]
> Same here with Python 3.7 and Windows 10.
> (mypython) C:\Users\gixig\mypython\Scripts>pip install C:\Users\...\blis-0.2.4-cp37-cp37m-win_amd64.whl
> ERROR: blis-0.2.4-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

I finally got understand with this error, maybe you should try to check your Python version(32 or 64?). As this package is for Python(64bit), if one install it with Python(32bit), the error would appear._(:з)∠)_

**Comment by honnibal** [comment]
I think yeyoushan is correct, and it's an issue of making sure you're on a 64-bit Python.

**Comment by tguttenb** [comment]
Hi, I am trying to get started on spacy.  I am using 2.7, and it installed but I am having some persistent problems importing because it doesn't find thinc 7.3.1....then thinc doesn't install because it is missing several requirements.  I have been adding these one at a time, but then I get to blis and get stuck.  

I don't see a whl file for 2.7 window, and when I try to run it using the tar.gz file I get the below error:

Command "python setup.py egg_info" failed with error code 1....

I tried upgrading my set up tools, but it says it is already updated.  I get around this in most case by using the whl file, but don't see the right file for my environment.  Any advice?

**Comment by FilipeGalva** [comment]
> Hi, I am trying to get started on spacy. I am using 2.7, and it installed but I am having some persistent problems importing because it doesn't find thinc 7.3.1....then thinc doesn't install because it is missing several requirements. I have been adding these one at a time, but then I get to blis and get stuck.
> 
> I don't see a whl file for 2.7 window, and when I try to run it using the tar.gz file I get the below error:
> 
> Command "python setup.py egg_info" failed with error code 1....
> 
> I tried upgrading my set up tools, but it says it is already updated. I get around this in most case by using the whl file, but don't see the right file for my environment. Any advice?

Same problem here: installed visual c++ 14.0 and made some progress by installing the other spacy wheels, but I'm stucked in this blis_compiler
